name: Exercice de cache
on: push

jobs: 

  cours1: 
    name: Exercice de workflow
    runs-on: ubuntu-latest
    steps:
      - name: get the code !
        uses: actions/checkout@v4
      - id: mise-en-cache
        uses: actions/cache@v4
        with: 
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
        # voir aussi : le cache de actions/setup-node
        # name: setup node
        # uses: actions/setup-node@v4
        # with: 
        #   cache: 'npm'
      - name: installation des node_modules
        if: steps.mise-en-cache.outputs.cache-hit != 'true'
        run: npm install
      - name: build
        run: npm run build
      - name: upload le resultat du build 
        uses: actions/upload-artifact@v4
        with: 
          name: mon-site
          path: .next/
  