name: Exercice de workflow
on: push

jobs: 

  exercice1: 
    name: Exercice de workflow
    runs-on: ubuntu-latest
    outputs: 
      result-test: ${{steps.run-test.results }}
    steps:
      - name: get the code !
        uses: actions/checkout@v4
      # - name: mis en cache 
      #   uses: actions/cache@v4
      #   with: 
      #     path: ~/.npm
      #     key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
        # voir aussi : le cache de actions/setup-node
        # name: setup node
        # uses: actions/setup-node@v4
        # with: 
        #   cache: 'npm'
      - name: installation des node_modules
        run: npm install
      - id: run-test
        run: npm run test
        continue-on-error: true
      # - name: build
      #   run: npm run build
      # - name: upload le resultat du build 
      #   uses: actions/upload-artifact@v4
      #   with: 
      #     name: mon-site
      #     path: .next/
      # - name: sommaire
      #   run: echo "Je suis push dans le summary" >> $GITHUB_STEP_SUMMARY
  
  exercice2: 
    name: On récupère les resultats des tests
    runs-on: ubuntu-latest
    needs: exercice1
    steps: 
      - name: get le résultat des tests
        run: | 
          echo "Les tests sont : $OUTPUT_TEST"
        env: 
          OUTPUT_TEST: ${{ needs.exercice1.outputs.result-test }}