name: Exercice de workflow
on: push
jobs: 
  exercice: 
    name: Exercice de workflow
    runs-on: ubuntu-latest
    steps:
      - name: get the code !
        uses: actions/checkout@v4
      - name: installation des node_modules
        run: npm install
      - name: build
        run: npm run build
      - name: upload le resultat du build 
        uses: actions/upload-artifact@v4
        with: 
          name: mon-site
          path: .next/

        