name: Workflow qui se déclenche lors de la création d'une issue 
on: 
    issues:
        types:
            - opened

jobs:
    commentaire: 
        runs-on: ubuntu-latest
        steps:
            - run: gh issue comment $ISSUE_URL --body "coucou from workflow"
              env: 
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                ISSUE_URL:  ${{ github.event.issue.html_url }}
    output: 
        runs-on: ubuntu-latest
        steps: 
            - name: sans env
              run: echo "Nouvelle issue - (unsecured) ${{ github.event.issue.title }}"
            - name: avec env
              env: 
                TITRE: ${{github.event.issue.title }}
              run: echo "Nouvelle issue - (secured) $TITRE"

            
