name: Workflow qui appelle le workFlow output
on: 
    workflow_dispatch:

jobs: 
    job1:
        name: Appelle le 1er workflow
        uses: Franfran62/workflows/.github/workflows/workflow-output.yml@main
    job2: 
        name: Affiche les outputs du premier workflow
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - id: echo-les-outputs
              run: echo "${{needs.job1.outputs.variable1 }} ${{needs.job1.outputs.variable2 }}" 
            - id: echo-les-needs
              run: echo "$NEEDS_JSON"
              env: 
                NEEDS_JSON: ${{ toJSON(needs) }}
    